# Generated by Django 5.1.4 on 2026-04-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_category_id_alter_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
